import 'package:flutter/material.dart';

final List<Map<String, dynamic>> facultySubjects = [
  {
    "label": "Artificial Intelligence - Programming Tools",
    "value": "artificial_intelligence_programming_tools",
    "icon": Icons.psychology,
    "description": "Learn AI programming tools and techniques",
    "color": Colors.orange,
    "category": "AI & Data",
    "units": [
      {"name": "Unit 1"},
      {"name": "Unit 2"},
      {"name": "Unit 3"},
      {"name": "Unit 4"},
    ],
  },
  {
    "label": "Cloud Computing",
    "value": "cloud_computing",
    "icon": Icons.cloud,
    "description": "Explore cloud computing concepts and practices",
    "color": Colors.blue,
    "category": "Engineering",
    "units": [
      {"name": "Unit 1"},
      {"name": "Unit 2"},
      {"name": "Unit 3"},
      {"name": "Unit 4"},
    ],
  },
  {
    "label": "Compiler Design",
    "value": "compiler_design",
    "icon": Icons.build,
    "description": "Learn about compiler construction and design",
    "color": Colors.redAccent,
    "category": "Core Systems",
    "units": [
      {"name": "Unit 1"},
      {"name": "Unit 2"},
      {"name": "Unit 3"},
      {"name": "Unit 4"},
    ],
  },
  {
    "label": "Computer Networks",
    "value": "computer_networks",
    "icon": Icons.network_check,
    "description": "Study computer networking concepts and protocols",
    "color": Colors.lightBlue,
    "category": "Networking",
    "units": [
      {"name": "Unit 1"},
      {"name": "Unit 2"},
      {"name": "Unit 3"},
      {"name": "Unit 4"},
    ],
  },
  {
    "label": "Computer Organization and Architecture",
    "value": "computer_organization_and_architecture",
    "icon": Icons.computer,
    "description": "Understand computer architecture and organization",
    "color": Colors.green,
    "category": "Core Systems",
    "units": [
      {"name": "Unit 1"},
      {"name": "Unit 2"},
      {"name": "Unit 3"},
      {"name": "Unit 4"},
    ],
  },
  {
    "label": "Machine Learning",
    "value": "machine_learning",
    "icon": Icons.memory,
    "description": "Introduction to machine learning concepts and algorithms",
    "color": Colors.deepPurple,
    "category": "AI & Data",
    "units": [
      {"name": "Unit 1"},
      {"name": "Unit 2"},
      {"name": "Unit 3"},
      {"name": "Unit 4"},
    ],
  },
  {
    "label": "Theory of Computation",
    "value": "theory_of_computation",
    "icon": Icons.functions,
    "description": "Study automata, formal languages, computability, and complexity",
    "color": Colors.indigo,
    "category": "Core Systems",
    "units": [
      {"name": "Unit 1"},
      {"name": "Unit 2"},
      {"name": "Unit 3"},
      {"name": "Unit 4"},
    ],
  },
  {
    "label": "Wireless Networks",
    "value": "wireless_networks",
    "icon": Icons.wifi,
    "description": "Study wireless communication and networking",
    "color": Colors.cyan,
    "category": "Networking",
    "units": [
      {"name": "Unit 1"},
      {"name": "Unit 2"},
      {"name": "Unit 3"},
      {"name": "Unit 4"},
    ],
  },
  {
    "label": "Internet of Things",
    "value": "internet_of_things",
    "icon": Icons.sensors,
    "description": "Learn about connected devices, sensor networks, and IoT applications",
    "color": Colors.deepOrange,
    "category": "Engineering",
    "units": [
      {"name": "Unit 1"},
      {"name": "Unit 2"},
      {"name": "Unit 3"},
      {"name": "Unit 4"},
    ],
  },
  {
    "label": "C Programming",
    "value": "c_programming",
    "icon": Icons.code,
    "description": "Master the fundamentals of C programming language",
    "color": Colors.blueGrey,
    "category": "Programming",
    "units": [
      {"name": "Unit 1"},
      {"name": "Unit 2"},
      {"name": "Unit 3"},
      {"name": "Unit 4"},
    ],
  },
];